name: Maven Package
'on':
  release:
    types:
    - created
  workflow_dispatch: {
    }
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set environment variables for Maven auth
      run: |-
        echo "GITHUB_ACTOR=aeromac" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
    - name: Set up custom Maven settings
      run: |-
        mkdir -p ~/.m2
        cp .github/settings.xml ~/.m2/settings.xml
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
        server-id: github-reuise-webstyles
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
